### ISSUE TITLE
OVO API change

### ISSUE THREAD

**Issue by pg-nut** [ThePaulAdams/OvOEnergy#2]
On 17th April changes to the OVO API stop the script from retrieving data. Would it be possible to update the script for these changes?

**Comment by ThePaulAdams** [comment]
Unfortunately I'm no longer an OVO customer so not aware of any of the API Changes and don't have credentials to test anymore.

I'll have a quick look but not sure If i'd be able to invest much time to try and fix it
If you are capable I'd be more than happy to accept a PR to resolve

**Comment by pg-nut** [comment]
Thanks for the quick response, it’s beyond my skill set unfortunately!

**Comment by pg-nut** [comment]
The URL to retrieve half hourly data has changed to:

https://smartpaymapi.ovoenergy.com/usage/api/half-hourly/

This gets the script working again.
